### ISSUE TITLE
Environment Variables Support out of the box with next 9.4

### ISSUE THREAD

**Issue by cristian05** [pankod/next-boilerplate#101]
https://github.com/pankod/next-boilerplate/blob/56f958798671ebce1d6615dedc924dafbf4d0b8c/next.config.js#L5

This dependency its no necesary with [last Nextjs update](https://nextjs.org/blog/next-9-4#new-environment-variables-support). With this update the management of environmen variables is easier and intuitive.

**Comment by omeraplak** [comment]
Hi @cristian05 ,
Thanks for reaching us. We have added this feature to our backlog. We’ll update it soon.

**Comment by omeraplak** [comment]
@cristian05 Hi,
We've updated master branch. Thanks for your notice.
