### ISSUE TITLE
Bundle Analyzer deprecated

### ISSUE THREAD

**Issue by vitaliemiron** [pankod/next-boilerplate#103]
zeit/next-bundle-analyzer - is deprected and was moved to @next/bundle-analyzer
[More info](https://github.com/zeit/next-plugins/tree/master/packages/next-bundle-analyzer)
and [here](https://github.com/zeit/next-plugins/issues/640)
I will try to fix and create a PR.

**Comment by omeraplak** [comment]
@vitaliemiron Hi,
Thanks for reaching us. We look forward to your contributions! 🎉
