### ISSUE TITLE
Missing 404 page

### ISSUE THREAD

**Issue by ehsanagh** [pankod/next-boilerplate#107]
with a fresh install we get he below warning.

`Warning: You have added a custom /_error page without a custom /404 page. This prevents the 404 page from being auto statically optimized.
see here for info: https://err.sh/next.js/custom-error-no-custom-404`

**Comment by aliemir** [comment]
I think this error is related to a bug in Next.js. Bumping Next version to 9.3.6 or above may solve your issue.

https://github.com/vercel/next.js/pull/12061

**Comment by ehsanagh** [comment]
No, Didn't solve yet,
I use the latest version but still get the warning.

 "next": "^9.4.4",
