### ISSUE TITLE
TypeError: Cannot read property 'kind' of undefined     at getErrorSpanForNode

### ISSUE THREAD

**Issue by dolnma** [pankod/next-boilerplate#108]
Hello, i have a problem with error after build (start:dev command), where error "`TypeError: Cannot read property 'kind' of undefined at getErrorSpanForNode (C:\work\rankseacom\node_modules\typescript\lib\typescript.js:13856:22)`
" appears.
Anyone with the same problem?

**Comment by hzcodertr** [comment]
+1

**Comment by nashpb** [comment]
+1

**Comment by CherIgor** [comment]
+1
"next":  "9.4.4",
"ts-node": "8.10.2",
"typescript": "3.9.5",

**Comment by defracted** [comment]
Same issue for me here,

next: 9.4.4
typescript (tried all of those): 3.9.5, 3.9.4, 3.9.3, 3.9.2

The issue seems to appear after TS f version 3.8.3, I tried using 3.8.3 and it works great.

**Comment by sawitsingsopha** [comment]
downgrade typescript to "typescript": "3.1.6"

**Comment by kdeenanauth** [comment]
If anyone is still running into this - upgrading to latest Typescript (4.1.2) also works.
