### ISSUE TITLE
Nextjs built-in api routes

### ISSUE THREAD

**Issue by mehmetsefabalik** [pankod/next-boilerplate#112]
Nextjs supports built-in api routes (https://nextjs.org/docs/api-routes/introduction), I think it would be better if it is applied to this repo.

**Comment by omeraplak** [comment]
@mehmetsefabalik Hi,
Thanks for reaching us. Could you do that?

**Comment by mehmetsefabalik** [comment]
I will take a look at this issue in the evening.
