### ISSUE TITLE
[Question]: How to handle private routes in your template?

### ISSUE THREAD

**Issue by adilmedibookr** [pankod/next-boilerplate#115]
Hi Guys, 

Great work, this template is really a great boilerplate. I have one question only for now.

How can we achieve the private routes in this template?

I tried the HOC component but it's not working due to getInitialProps in pages. There is no store in ctx object. The same thing tried with Component also. but got the same error.

So any idea for this in your mind?

Thank you.

Regards,
M. Adil

**Comment by burcukaragozzz** [comment]
In the getinitialprops of the pages, we check with the cookie. Like this,
> 
export const HandleAuthenticatedPage = async (ctx: ReduxNextPageContext) => {
    try {
        if (ctx?.res) {
            await ctx.store?.dispatch?.(await ProfileActions.GetProfile());
        }
    } catch (e) {
        if (e.status === 401 || e.message === "AuthenticationError") {
            Nookies.destroy(ctx, "account", { path: "/" });
            RedirectIfNotAuthorized(ctx);
        }
    }
};

**Comment by burcukaragozzz** [comment]
In the getinitialprops of the pages, we check with the cookie. Like this,

> export const HandleAuthenticatedPage = async (ctx: ReduxNextPageContext) => {
>     try {
>         if (ctx?.res) {
>             await ctx.store?.dispatch?.(await ProfileActions.GetProfile());
>         }
>     } catch (e) {
>         if (e.status === 401 || e.message === "AuthenticationError") {
>             Nookies.destroy(ctx, "account", { path: "/" });
>             RedirectIfNotAuthorized(ctx);
>         }
>     }
> };

**Comment by burcukaragozzz** [comment]
In the getinitialprops of the pages, we check with the cookie.

**Comment by Usama-Tahir** [comment]
First of all, congratulations on such an awesome boilerplate. I want to use client-side rendering so getinitialprops is not the right fit for me. Also checking if the user is authorized or not on each page seems like a repetitive task. Do you guys plan on adding a protected route to this template?

**Comment by BatuhanW** [comment]
@Usama-Tahir You could write a hook to check authenticated user and redirect if not. We might be adding it in the future.

**Comment by Usama-Tahir** [comment]
@BatuhanW thank you for your suggestion. How about creating a higher-order component and wrapping each protected page with this?
