### ISSUE TITLE
How do I get the call to api?

### ISSUE THREAD

**Issue by safacaki** [pankod/next-boilerplate#12]
Hi, reviewing your boilerplate and i not seen call api example. How do I get the call to api? Is there a special method you use? Axios or should I use derivatives?

**Comment by omeraplak** [comment]
Hi @safacaki ,
Thanks for reaching us. We have added this feature to our backlog. We’ll update it soon. 
But if you don’t want to wait, you can integrate fetch library with this following example https://github.com/zeit/next.js/tree/canary/examples/data-fetch

If you integrate "fetch" on your fork, you can open the pull request.

**Comment by safacaki** [comment]
Thanks

**Comment by omeraplak** [comment]
Hi @scaki ,
We have added "fetch" example with unit tests. 

You can checkout example API of "Planetary"
https://github.com/pankod/next-boilerplate/blob/master/src/Services/API/Planetary.ts

Also we’ve added example action,
https://github.com/pankod/next-boilerplate/blob/master/src/Actions/HomeActions.ts#L26

Feel free to contact us if you need anything.

**Comment by scaki** [comment]
Hi @omeraplak  I didn't have time to deal with this, thank you :)
