### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by puskuruk** [pankod/next-boilerplate#13]
Hi!

I really find your boilerplate useful and I added to => https://github.com/dzharii/awesome-typescript . 

Now I think If you added contributing guide it will be useful for you and who want to improve your boilerplate.

If you want I can help for creating an issue template and creating contributing file.

Have a nice day!

**Comment by omeraplak** [comment]
Hi @puskuruk ,
Thanks for reaching us. We’re so happy for your contribution. 
We’d be so happy if you could add issue template and create contributing file.
