### ISSUE TITLE
Poor performance in Lighthouse

### ISSUE THREAD

**Issue by baj84** [pankod/next-boilerplate#149]
Hi,

When using the default code with a very basic page that just returns a single div the performance is not great (81/100). This then obviously decreases quickly when you start to add in additional elements/logic.

Is there anything that can be done to speed things up?
<img width="1674" alt="Screen Shot 2021-04-22 at 15 40 04" src="https://user-images.githubusercontent.com/2744292/115661673-27df8200-a381-11eb-95f7-b37a89fc3a33.png">

Cheers

**Comment by omeraplak** [comment]
Hi @baj84 ,
We have [stopped developing](https://github.com/pankod/next-boilerplate#bye-bye-next-boilerplate-welcome-to-superplate) the next-boilerplate project. You can create a nextjs project with the same features using [superplate](https://github.com/pankod/superplate). 
For lighthouse optimization, we recommend you to follow nextjs analytics, [https://nextjs.org/analytics](https://nextjs.org/analytics)
