### ISSUE TITLE
Error on running project

### ISSUE THREAD

**Issue by prakash-ar** [pankod/next-boilerplate#156]
Hi

Thanks for the wonder full boiler plate combo.

I have cloned the boiler plate in my local. 
Then i have given npm install.
npm run start:dev
In this point I am getting error as below screenshot
Please help me to get fix this
Branch:master
![error js](https://user-images.githubusercontent.com/61845603/121797905-ccbf6280-cc40-11eb-9f6f-0e3d1f41bc32.png)

**Comment by omeraplak** [comment]
Hi @prakash-ar ,
We have stopped developing the next-boilerplate project. You can create a nextjs project with the same features using [superplate](http://github.com/pankod/superplate).
