### ISSUE TITLE
Migrate to Eslint

### ISSUE THREAD

**Issue by BatuhanW** [pankod/next-boilerplate#24]
Since TypeScript team will be focusing on making eslint better, it could be nice to migrate to eslint.

https://eslint.org/blog/2019/01/future-typescript-eslint

**Comment by omeraplak** [comment]
Hi @BatuhanW ,
Thanks for reaching us. We’re gonna investigate it. And we’ll update it soon. Feel free to contact us if you need anything.

**Comment by BatuhanW** [comment]
I cand send a PR to migrate to Eslint and setup prettier as well if you prefer.

**Comment by omeraplak** [comment]
@BatuhanW hi, 
We’d be so happy if you could open PR.

**Comment by BatuhanW** [comment]
Fixed with https://github.com/pankod/next-boilerplate/pull/27
