### ISSUE TITLE
redux-persist failed to create sync storage. falling back to memory storage.

### ISSUE THREAD

**Issue by Mezhinsky** [pankod/next-boilerplate#3]
while yarn start:dev ---> redux-persist failed to create sync storage. falling back to memory storage.

**Comment by omeraplak** [comment]
Hi @Mezhinsky, 
Thanks for your warning. We removed redux-persist dependency.
 
We thought about adding it when we were making boilerplate but then it seemed us unnecessary and we’ve deleted all the dependencies. You can use the latest version of it on master branch.
