### ISSUE TITLE
No integration saga?

### ISSUE THREAD

**Issue by Alvazz** [pankod/next-boilerplate#34]
how can i use saga in this boilerplate? 

thx!

**Comment by BatuhanW** [comment]
We have plans to make our boilerplate compatible with both thunk and saga through cli. Unfortunately it's not implemented yet. However there is HOC which may help. You can give it a try;

https://github.com/bmealhouse/next-redux-saga

Please let us know how it works and we are always open to PRs if you want to contribute. You can reopen this issue if you have followup questions!

**Comment by Alvazz** [comment]
@BatuhanW thank you for your reply, when can we finish this work?

**Comment by icodifytechnology** [comment]
@BatuhanW here's the boilerplate of redux-saga.
https://github.com/ms13suz/next-boilerplate

**Comment by ms13suz** [comment]
@BatuhanW here's the boilerplate of redux-saga.
https://github.com/ms13suz/next-boilerplate

**Comment by BatuhanW** [comment]
@ms13suz You could at least `fork` our repository before cloning the entire repo and writing something like;

`Written by Suzan Thapa suzanthapa80@gmail.com, September 2020`

**Comment by ms13suz** [comment]
Sorry for that i will remove it.

**Comment by ms13suz** [comment]
I am extremely sorry. It was just only for testing purpose so I forgot to change. There is changed in readme file . Please kindly inform me if you want to delete this repository.

Thank you
