### ISSUE TITLE
next-i18next

### ISSUE THREAD

**Issue by lehuuhienn** [pankod/next-boilerplate#48]
I like so much this boilerplate, but i need next-i18next, you can help me config it, thanks you :D

**Comment by omeraplak** [comment]
Hi @lehuuhienn ,
Thanks for reaching us. We have added this feature to our backlog. We’ll update it soon.
But if you don’t want to wait, you can integrate next-i18next library with this following example https://github.com/isaachinman/next-i18next

If you integrate "next-i18next" on your fork, you can open the pull request.

**Comment by omeraplak** [comment]
Hi @lehuuhienn ,
We've merged to master.  You can use "i18n" feature. Feel free to contact us if you need anything.
