### ISSUE TITLE
css is not working when i change page

### ISSUE THREAD

**Issue by skptricks** [pankod/next-boilerplate#50]
css layout is not working when i change the page by clicking on any link. Page is getting display in disorganized manner.

**Comment by omeraplak** [comment]
Hi @skptricks ,
Thanks for reaching us. We’re gonna investigate it. And we’ll update it soon. Feel free to contact us if you need anything.

**Comment by BatuhanW** [comment]
@skptricks Hi, we are working on 2nd version of this boilerplate, this should be fixed there. Can you stay tuned and let us know once we share v2?

**Comment by richardblondet** [comment]
Hello @BatuhanW, thanks for the great work. When is this V2 will be available? Cheers

**Comment by BatuhanW** [comment]
@richardblondet It will be available today! 🎉
