### ISSUE TITLE
Any plans on integrating feathersjs?

### ISSUE THREAD

**Issue by AmitJoki** [pankod/next-boilerplate#57]
I think this boilerplate will be more complete if we could also add feathersjs which is a lightweight API framework. Since it already uses Express, I think it will be a nice add on and make this boilerplate more fullstack.

**Comment by BatuhanW** [comment]
@AmitJoki We want this boilerplate to focus only on client side, so we aren't eager to add such improvements. But we are always open to contributions, PRs.
