### ISSUE TITLE
No html tags being shown on page source after building the boilerplate.

### ISSUE THREAD

**Issue by ravi0402** [pankod/next-boilerplate#76]
After building the nextjs boilerplate, 
I am not getting the the `<div, <a>` and other elements on page source. Just getting   
`<body><div id="__next"></div>   `

This won't be useful for SEO right. The web crawling bots won’t be able to extract and index the required data.  How can I fix this?  Thanks.

**Comment by futuredayv** [comment]
Can you please provide us a repo or a stackblitz demo so we can reproduce the problem.
