### ISSUE TITLE
Is there a way to use it without Typescript and redux?

### ISSUE THREAD

**Issue by ertejaspatel** [pankod/next-boilerplate#79]
Thanks for the awesome boilerplate - Is there any easy way to use this without typescript and redux?

There is possibility of using Mobx as state management.

**Comment by omeraplak** [comment]
Hello @ertejaspatel ,
Unfortunately there is no easy way to do this.

**Comment by mohsin51** [comment]
Nice boilerplate but there should be non-typescript version too for this.
