### ISSUE TITLE
how we can load custom font?

### ISSUE THREAD

**Issue by krish-dev** [pankod/next-boilerplate#80]
How this get work with scss?

`@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 300;
  src: url('assets/fonts/roboto-v20-latin-300.eot'); /* IE9 Compat Modes */
  src: local('Roboto Light'), local('Roboto-Light'),
       url('assets/fonts/roboto-v20-latin-300.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
       url('assets/fonts/roboto-v20-latin-300.woff2') format('woff2'), /* Super Modern Browsers */
       url('assets/fonts/roboto-v20-latin-300.woff') format('woff'), /* Modern Browsers */
       url('assets/fonts/roboto-v20-latin-300.ttf') format('truetype'), /* Safari, Android, iOS */
       url('assets/fonts/roboto-v20-latin-300.svg#Roboto') format('svg'); /* Legacy iOS */
}`

**Comment by futuredayv** [comment]
Hi! @krish-dev,

The template you attached is for `icon fonts`. If you want to use a custom font in your web application you can edit your meta tags by importing `Head` from `next/document`. `pages/__document` is the very beginning of your application and could be the best place to implement these. We encourage you to use a CDN for that.

You can use it just like any other React Component:

```jsx
<Head>
    <link
        href="https://fonts.googleapis.com/css?family=Montserrat:400,500,500i,600,700,800&display=swap"
        rel="stylesheet"
    />
</Head>
```

**Comment by futuredayv** [comment]
Hey @krish-dev! 

I came back with some documentation 📃! Now, if you really want to use your fonts locally I can suggest you 2 different brief solutions:

First of all install [`next-fonts`](https://www.npmjs.com/package/next-fonts):
```sh
~$ npm i next-fonts
```

Then in your `next.config` import it right away:
```js
const withFonts = require("next-fonts");
```

Later in your `next.config` file, append it in just like other plugins:
```js
withPlugins(
    [[withFonts], [withCSS], [withSass], [withBundleAnalyzer]],
    nextConfig
)
```


> __Friendly Reminder__
>
> Do NOT forget to use __absolute paths__ in your src url("/...")


## 👨‍🎨 Sass
If you prefer to use Sass create a traditional `@font-face`:
```css
@font-face {
    font-family: "Muli";
    font-style: normal;
    font-weight: 400;
    src: url("/static/fonts/Muli-Regular.ttf") format("truetype");
}
```

## 💅 Styled Components
And if you prefer to go with styled-components I suggest you to create a global style:

```jsx
import { createGlobalStyle } from "styled-components";

const GlobalStyles = createGlobalStyle`
    @font-face {
        font-family: "Muli";
        font-style: normal;
        font-weight: 400;
        src: url("/static/fonts/Muli-Regular.ttf") format("truetype");
    }
`;
```

Then place it in very beginning of your project `pages/_document`:
```jsx
render() {
    return (
        <Html>
            <Head />
            <body>
                <GlobalStyles />    // Here is where magic happens! 🌟 
                <Main />
                <NextScript />
            </body>
        </Html>
    );
}
```

📬 Please don't hesitate to ask any further questions!
