### ISSUE TITLE
Module resolution in tsconfig alias is not working

### ISSUE THREAD

**Issue by cristian05** [pankod/next-boilerplate#82]
## Error
I just add `Utils/logger` folders in `src`. but when i want to use a file inside that foler in `server/index` with alias throws the following error:

`Error: Cannot find module '@Utils/logger'`

can't solve the imports either, if I use absolute routes and no aliases it works. the problem is only with this folder.

## Changes made 

**`ts.config`**

`
{
  "compilerOptions": {
     "baseUrl": ".",
     "paths": {
        "@Utils/*": ["src/Utils/*"],
        "@Utils": ["src/Utils"]
      }
  }
}
`

**`.babelrc`**

`
{
  "presets": ["next/babel"],
  "plugins": [
    [
      "module-resolver",
      {
        "root": ["./"],
        "alias": {
          "@Utils": "./src/Utils"
        }
      }
    ]
  ]
}
`

**Comment by BatuhanW** [comment]
@cristian05 Express isn't configured to respect alias paths in tsconfig.json or .babelrc, so you should import this file in a traditional way. (`import logger from '../src/Utils')

I also suggest, if you are using this logger only for server, perhaps moving it to `server` folder is better.
