### ISSUE TITLE
What is the purpose of using `declare` and `export` together?

### ISSUE THREAD

**Issue by cristian05** [pankod/next-boilerplate#88]
## src/Components/Footer/Footer.d.ts 

```
declare namespace IFooter {
    export interface IProps {}
}

export { IFooter };
```

**Comment by futuredayv** [comment]
Hi @cristian05 !

You need these typings exported to type your variables statically, so make sure your editor assist you while you're writing or building.

**Comment by futuredayv** [comment]
Also you don't need to export your typings declared in namespace or module.

```ts
export declare namespace IFooter {
    interface IProps {}
}
```

**Comment by cristian05** [comment]
@futuredayv in the components folder its being used `export` within the `namespace` in files like `Footer.d.ts` or `Navbar.d.ts`. it's still not clear to me why you should use `export` and `declare`, if once you use declare with an interface, namespace or module that declaration automatically are available in the global scope its not necesary use `export` to use it. Nor is it necessary to use export to make the editor assist you while you're writing or building.

**Comment by futuredayv** [comment]
Hey @cristian05,

It's been awhile and I couldn't figure out how to use typings in a separated file without exporting. Can you please share me a repo or file snippets? I'd like to examine how you'd use typings without exporting.

**Comment by cristian05** [comment]
@futuredayv 

> In TypeScript, just as in ECMAScript 2015, any file containing a top-level import or export is considered a module. Conversely, a file without any top-level import or export declarations is treated as a script whose contents are available in the global scope (and therefore to modules as well).
https://www.typescriptlang.org/docs/handbook/modules.html

then according to the above, all you need is to remove all `import` and `export` from the file and automatically the declarations within the file will be available in the global scope.

## src/Components/Footer/Footer.d.ts
```
declare namespace IFooter {
  interface IProps {}
}
```
## src/Components/Footer/index.tsx

```
import React from 'react';

const Footer: React.FunctionComponent<IFooter.IProps> = (): JSX.Element => (
  <div className="footer">Footer</div>
);

export { Footer };
```
As you note here, you can still use `IFooter.Iprops` without having to import it into the file. **This pollute the Global namespace.**

**Comment by futuredayv** [comment]
Hey @cristian05! 🖐

Thank you for your detailed response. That is awesome! 🎉We'd love to refactor all of our typings in this way but we need to work with some cases to make sure it's better. It would be great if you share your thoughts on *pros and cons of typing through global scope*.

**Comment by cristian05** [comment]
@futuredayv 

## pros
The TypeScript code we write is in the global scope by default. If we have multiple files in a project, the variables, functions, etc. written in one file are accessible in all the other files. So its easier to use types defined in other files.

## cons
Your are polluting the `global namespace`, anybody can easily override variables declared in the global scope without even knowing they are doing so. This is a dangerous space as **it can lead to conflicts/erros in the code**.

_______________________________________________________________

The thing here is why use `export` and declare `together`?

> Most large/mature TypeScript libraries avoid relying on ambient declarations and instead export anything that needs to be reused outside of the current file. For example, the Angular codebase has an interfaces.ts file for each module which is imported into each file that needs to reference the interfaces: https://stackoverflow.com/questions/48690533/typescript-declare-vs-export-best-practices

> "Magically available interfaces" or global types is highly discouraged and should mostly be left to legacy. Also, you should not be using ambient declaration files (e.g. d.ts files) for code that you are writing. These are meant to stand-in the place of external non-typescript code (essentially filling in the typescript types into js code so that you can better integrate it with javascript).
>For code you write you should be using plain .ts files to define your interfaces and types. https://stackoverflow.com/questions/42233987/how-to-configure-custom-global-interfaces-d-ts-files-for-typescript

**Comment by omeraplak** [comment]
@cristian05 Hi,

It has been a long time since we started next-boilerplate project. We are proud that it helped many frontend developers around the globe to speed up their frontend development cycles.

In time, we took valuable lessons from our experience and the community feedback:

- There are infinite number of frontend technologies and it's impossible to combine everything in a single boilerplate product.
- The project is hard to maintain with tons of external dependencies.
To tackle the complexity problem we started a new project from scratch. We call it "superplate" - the frontend boilerplate with superpowers.

It's built on top of a plugin architecture and allows you integrate your own tools and best practices with ease. It also includes more than 30 built-in plugins of your favorite tools.

superplate's default framework is Next.js, so you can start using it immediately instead of next-boilerplate. More framework targets are coming soon.

You may checkout the project from the [repo page](https://github.com/pankod/superplate) or [documentation](https://pankod.github.io/superplate/).
