### ISSUE TITLE
I'm using VSCode Jest extension

### ISSUE THREAD

**Issue by KInGATiLLa** [pankod/next-boilerplate#95]
And Jest extension show me this error. Whats wrong it?. How to fix this error?
Environment:
Windows10 64bit
Node :12.16.1
Vscode :1.44.2
Jest extension: 3.1.1

![image](https://user-images.githubusercontent.com/17881842/79967909-06279280-84c2-11ea-9b3f-b7d48a07b152.png)

**Comment by omeraplak** [comment]
@KInGATiLLa Hi,
Thank you reach us! You should add "@Server" annotation on jest.config.js

like this,
` moduleNameMapper: {
        "\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$":
            "<rootDir>/test/mocks.ts",
        "\\.(css|less|scss|html)$": "<rootDir>/test/mocks.ts",
        **"^@(Server)(.*)$": "<rootDir>/server/$2",**
        "^@(Test)(.*)$": "<rootDir>/test/$2",
        "^@([A-Z].*)$": "<rootDir>/src/$1",
    },
`

**Comment by KInGATiLLa** [comment]
Thank you, 
Let me ask you something. That is when i changed this repo code instantly. Can i push my changes. 
If no, why no ?

**Comment by omeraplak** [comment]
@KInGATiLLa Yes, you can! 🎉
