### ISSUE TITLE
Unnecessary options in jest configuration file

### ISSUE THREAD

**Issue by cristian05** [pankod/next-boilerplate#97]
https://github.com/pankod/next-boilerplate/blob/02230f3cbfcf5a1cf796c5c6789baaa8ff9ae527/jest.config.js#L2

https://github.com/pankod/next-boilerplate/blob/02230f3cbfcf5a1cf796c5c6789baaa8ff9ae527/jest.config.js#L3

these rules are set by default by jest [configuration](https://jestjs.io/docs/en/configuration), and are more inclusive in some cases if you use the `__test__` pattern folder or if you reference the `json` file in any of your tests.

### moduleFileExtensions [array<string>]
Default: `["js", "json", "jsx", "ts", "tsx", "node"]`

### testMatch [array<string>]
(default: `[ "**/__tests__/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).[jt]s?(x)" ]`)

**Comment by omeraplak** [comment]
@cristian05 Hi,
Thank you for reaching us! You are right, we've fixed. (8acebc337fc3954421ca7669aba1e9a59bd8fcb2)
